name:                dromedary
version:             0.0.0.1
github:              "adamwespiser/dromedary"
license:             BSD3
author:              "Adam Wespiser"
maintainer:          "Adam Wespiser"
copyright:           "2020 Adam Wespiser"

extra-source-files:
- README.md
- ChangeLog.md


dependencies:
- base >= 4.7 && < 5
- async
- containers
- mtl
- stm
- transformers
- text
- time
- unliftio
- unliftio-core

library:
  source-dirs: src

executables:
  dromedary:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dromedary
    - unliftio-core

tests:
  dromedary-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dromedary
